sudo: required
services:
 - docker

before_install:
 - docker build -t saee/docker-node -f Dockerfile.dev .


deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker"
 env: "Docker-env"
 bucket_name: elasticbeanstalk-ap-south-1-285651893026
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY

