version: "3"
services:
 web:
  build: 
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "100:3000"
  volumes:
   - .:/app

 test:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - .:/app
  command: ["npm", "run", "test"]
